name: Deploy to GitHub Pages

# Run workflow on every push to the main branch
on:
  push:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code form the master branch
    - uses: actions/checkout@v2
    
    # sets up .NET Core SDK 3.1
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1

    # publishes Blazor project to the release-folder
    - name: Publish .NET Core Project
      run: dotnet publish -c Release -o release --nologo
    
    # changes the base-tag in index.html from '/' to 'roblox-game-list' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to roblox-game-list
      run: sed -i 's/<base href="\/" \/>/<base href="\/roblox-game-list\/" \/>/g' release/wwwroot/index.html
      
    # change all framework files *.dll to *.bin
    - name: Renaming dll to bin
      run: |
        cd release/wwwroot
        for f in _framework/_bin/*; do mv "$f" "`echo $f | sed -e 's/\.dll/.bin/g'`"; done
        sed -i 's/\.dll"/.bin"/g' _framework/blazor.boot.json
        sed -i 's/\.dll"/.bin"/g' service-worker-assets.js

    # remove pre-compressed files
    - name: Remove pre-compressed
      run: |
        cd release/wwwroot
        rm service-worker-assets.js.*
        rm _framework/blazor.boot.json.*

    # fixing integrity check
    - name: Fixing integrity check
      run: |
        cd release/wwwroot
        apt update && apt install -y --no-install-recommends jq
        cp ../../scripts/integrity.sh .
        chmod +x integrity.sh && ./integrity.sh
        rm integrity.sh
    
    # copy index.html to 404.html to serve the same file when a file is not found
    - name: copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
      
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
